### ISSUE TITLE
Add possibility to donate

### ISSUE THREAD

**Issue by openscript** [Js-Brecht/gatsby-plugin-ts-config#13]
I spent the whole day to typescriptify a Gatsby project of mine. Your plugin came in handy. I think there should be a donate button somewhere.

💪

**Comment by Js-Brecht** [comment]
Hey @openscript, I'm really glad you found my plugin useful.  TBH, I'd never really thought receiving any kind of donations, but as requested, I've added one to the readme (top & bottom).

Please let me know if you think of any features you think it could use, or if you run into any issues.  I've got plans right now to add a new utility that will allow for strongly typed plugin options in `gatsby-config` (discriminated unions don't work properly at the moment), as well as resolving/transpiling local plugins.
