### ISSUE TITLE
Forwarding the config object provided to gatsby-config.js

### ISSUE THREAD

**Issue by mshick** [Js-Brecht/gatsby-plugin-ts-config#16]
I noticed that `gatsby-config.ts` gets the config options provided by this plugin, but does not seem to receive the original config object passed to `gatsby-config.js` when working in a theme or plugin. Is there some way to access these in my `ts` config file?

**Comment by Js-Brecht** [comment]
The original config object?  I'm not sure I'm understanding you completely.

Are you saying you have a setup like this?

```js
// ./gatsby-config.js
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-plugin-ts-config',
      options: {
        configDir: '.gatsby',
      }
    },
    /** some other plugins */
  ]
};
```
```ts
// ./.gatsby/gatsby-config.ts

export default () => ({
  plugins: [
    /** some more plugins */
  ]
});
```

If you have your config split between your root `gatsby-config.js` and your `gatsby-config.ts` (aside from the config for `gatsby-plugin-ts-config`), then no.  The one in the root gets absorbed into Gatsby and isn't exposed to plugins.  I mean, you could always reach into the redux store by importing the static path, but I wouldn't recommend it.

If your root `gatsby-config.js` looks like this:
```js
// ./gatsby-config.js
const { generateConfig } = require('gatsby-plugin-ts-config');
module.exports = generateConfig({
  configDir: '.gatsby',
});
```

Then some of those options are passed to your `gatsby-config.ts`.  Including the paths of files that are imported by `gatsby-config.ts` and `gatsby-node.ts`.  If you needed the paths of files that are imported by plugins as well, then you may be interested in #14.

---

I may need more information about your setup to be much help.

**Comment by mshick** [comment]
If you export a function from `gatsby-config.js` it receives an object with the plugin config / options provided in the consuming gatsby instance. 

E.g., my gatsby project `web`:

```js
// gatsby-config.js
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-theme-my-theme`
      options: {
        foo: 'bar'
      }
    }
  ]
}
```

And in `gatsby-theme-my-theme`:

```js
// gatsby-config.js
module.exports = (themeOptions) => {
  console.log(themeOptions)
  // > { foo: 'bar' }
  return {
    siteMetadata: {...},
    plugins: [...]
  }
}
```

Ideally I would be able to pass those theme options to the `gatsby-config.ts` file I'm using through this plugin. Maybe something like:

```
export default ({projectRoot, pluginOptions, ...}) {
  return { siteMetadata: {}, plugins: [] }
}
```

I've made a quick workaround with a singleton, but that doesn't feel viable long-term.

Here's a real world example of the `gatsby-config.js` interface: [gatsby-theme-catalyst](https://github.com/ehowey/gatsby-theme-catalyst/blob/main/themes/gatsby-theme-catalyst-blog/gatsby-config.js#L3)

**Comment by Js-Brecht** [comment]
So your theme is going to be setting up `gatsby-plugin-ts-config` then?  In order for that to work, `gatsby-plugin-ts-config` would need to accept an arbitrary set of options and simply pass them on to your `gatsby-config.ts`.  It's a bit different, but it would be doable.

**Comment by mshick** [comment]
Yeah, I think that would do the trick.

**Comment by Js-Brecht** [comment]
Okay, I'm good with it.  I'll put it on the list of things to do, but it may be a week or two before I can get to it.  I have a lot on my plate right now, so when I have the time, I'll implement this.  I'm willing to take PR, though, if you needed it sooner; it shouldn't be too difficult to do.  There's not really any logic to implement; it's just updating interfaces and adding/initializing the property on the class that handles that stuff.

**Comment by mshick** [comment]
Awesome, thanks for considering, and I totally understand. I have a decent workaround in place now; I'm setting up my config-needed plugins in the `.js` file. 

And thanks for the great plugin. I'd used some ts-node hacks in the past to accomplish something like this, but your solution is elegant and rock solid.

**Comment by Js-Brecht** [comment]
@mshick Sorry it's taken so long to get back to this.  Been working on a launch, and it's been time consuming.

I've just opened PR #19.  It is published as `gatsby-plugin-ts-config@next`.  Please let me know if that is kind of what you had in mind.
