### ISSUE TITLE
Handling non-hoisted plugins

### ISSUE THREAD

**Issue by mikaelkolkinn** [Js-Brecht/gatsby-plugin-ts-config#17]
I ran into an issue that's quite similar to #12, but instead of being for locally developed plugins, it's for plugins residing in the "local" node_modules directory.
My project uses yarn workspaces, which has decided not to hoist one of the plugins used for my gatsby project.

Error message:
>Couldn't find the "gatsby-plugin-graphql-codegen" plugin declared in "/Users/mikael/git/portal-web/node_modules/gatsby-plugin-ts-config/gatsby-config.js".
>
>Tried looking for an installed package in the following paths:
> - /Users/mikael/git/portal-web/node_modules/gatsby/dist/bootstrap/load-themes/node_modules/gatsby-plugin-graphql-codegen
> - /Users/mikael/git/portal-web/node_modules/gatsby/dist/bootstrap/node_modules/gatsby-plugin-graphql-codegen
> - /Users/mikael/git/portal-web/node_modules/gatsby/dist/node_modules/gatsby-plugin-graphql-codegen
> - /Users/mikael/git/portal-web/node_modules/gatsby/node_modules/gatsby-plugin-graphql-codegen
> - /Users/mikael/git/portal-web/node_modules/gatsby-plugin-graphql-codegen
> - /Users/mikael/git/sit/node_modules/gatsby-plugin-graphql-codegen
> - /Users/mikael/git/node_modules/gatsby-plugin-graphql-codegen
> - /Users/mikael/node_modules/gatsby-plugin-graphql-codegen
> - /Users/node_modules/gatsby-plugin-graphql-codegen
> - /node_modules/gatsby-plugin-graphql-codegen
>
>not finished open and validate gatsby-configs - 2.904s

Folder structure:
<img width="314" alt="image" src="https://user-images.githubusercontent.com/3751736/89545896-393d2a00-d804-11ea-815e-8ed8837a20fc.png">

**Comment by Js-Brecht** [comment]
This has more to do with the way Gatsby itself resolves plugins, plus an unfortunate side effect of the way yarn does hoisting.

As Gatsby recurses through themes (assume your root project is a theme in this context, too), it will scope the require to the directory of that theme.  Since `gatsby-plugin-ts-config` acts as a type of proxy, it essentially “hosts” all of your default project’s plugins.  When Gatsby tries to resolve them, it tries to do it from the directory of `gatsby-plugin-ts-config`; in your case, that means it starts from the repo root and works up from there.

The resolve paths that it reported to you actually look wrong, considering the way it’s _supposed_ to behave.  Can you tell me what version of Gatsby you’re using?

I’ve actually addressed the issue of resolving proxied plugins in `gatsby-plugin-ts-config@next`?  In order to support yarn 2 and pnpm, I’ve added a feature that makes this plugin do its own plugin resolution, and it uses the default project directory to do it.  This way, by the time the plugin collection gets to Gatsby, the paths are already resolved.  This should work for your use case, too.

**Comment by mikaelkolkinn** [comment]
I'm using Gatsby 2.23.21 and Yarn 2.1.1.

Switching to `gatsby-plugin-ts-config@next` seemed to do the trick, thanks!

**Comment by Js-Brecht** [comment]
@mikaelkolkinn I wonder if you'd be willing to test out some of the other features described [here, and below](https://github.com/Js-Brecht/gatsby-plugin-ts-config/tree/plugin-resolver#gatsby-config-utilites).  There's also an additional `plugin` property included in the `endpoints` argument [here](https://github.com/Js-Brecht/gatsby-plugin-ts-config/tree/plugin-resolver#gatsby--as-a-function-parameters).  I don't know if there's anybody using it yet, but it's meant to provide a list of files that are used during bootstrap to other plugins for monitoring, mainly for things like query extraction; any plugin that wants to monitor plugin files should be able to consume that `endpoints` parameter, though.

I am tracking those changes in #14, and I've just been trying to get more testing into it before pushing it to production.  Haven't had the time to test thoroughly, so any help would be appreciated, even if it's just to say "yes, it all works correctly in a yarn monorepo".

**Comment by mikaelkolkinn** [comment]
Hi @Js-Brecht. As my project is just in its beginning, I have no real use for the more advanced functionality your plugin provides, and it is therefore hard for me to test these.

But I can at least say which parts of it I have used:
- gatsby-config.js: `module.exports = generateConfig({ configDir: "./src/gatsby" });`
- gatsby-config.ts: Nothing special. Instead of using your types, I just used the ones from the Gatsby package directly.
```typescript
import { GatsbyConfig } from "gatsby";

// Current working directory is /packages/frontend/src/gatsby/, not /packages/frontend/
const projectPath = path.resolve(__dirname, "..", "..");

export default {
  // ...
  plugins: [
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "images",
        path: `${projectPath}/src/images`,
      },
    },
    // ...
  ]
} as GatsbyConfig;
``` 
- gatsby-node.ts: Nothing special from your plugin here either, but here is the rough setup I'm using:
```typescript
import { CreatePagesArgs, GatsbyNode } from "gatsby";
import path, { resolve } from "path";

// @app/types here is an alias in tsconfig.json. I'm pleasantly surprised that this worked out of the box.
// These types are also generated using gatsby-plugin-graphql-codegen, so I'm also very happy that this works out of the box too.
import { SamplePagesQuery } from "@app/types";

// ...

export const createPages: GatsbyNode["createPages"] = async (args) => {
  await createSamplePages(args);
};
```

**Comment by Js-Brecht** [comment]
I see, very cool.

I'm a bit surprised that the alias works without any additional set up.  Babel does not resolve tsconfig aliases by default, and the setup for that has traditionally been a bit of a pain and has been lacking much of the functionality that is provided by `tsconfig` aliases.

I've recently created [babel-plugin-tsconfig-paths](https://github.com/Js-Brecht/babel-plugin-tsconfig-paths), and have considered adding it by default to the babel preset used by this plugin.  It uses [babel-plugin-module-resolver](https://www.npmjs.com/package/babel-plugin-module-resolver) for inspiration, but actually supports all of the functionality of `tsconfig.compilerOptions.paths`.  It does need some polishing before I add it, though.

On the other hand, if babel is supporting tsconfig aliases by default now, then my job just got easier.  I will have to do some experimenting.

**Comment by mikaelkolkinn** [comment]
@Js-Brecht Sorry, my bad on the aliases working out of the box. I forgot that I had installed [gatsby-plugin-tsconfig-paths](https://www.gatsbyjs.org/packages/gatsby-plugin-tsconfig-paths/) previously.

**Comment by Js-Brecht** [comment]
IIRC, that plugin only sets up `tsconfig-paths-webpack-plugin` in the webpack config.  Shouldn't have an effect on bootstrap 🤔.  Probably not an important distinction at this point, though.  I'm just glad it's working for you
