### ISSUE TITLE
Gatsby node ownership 

### ISSUE THREAD

**Issue by Js-Brecht** [Js-Brecht/gatsby-plugin-ts-config#2]
As mentioned [here](https://github.com/d4rekanguok/gatsby-typescript/issues/4#issuecomment-587290120), Gatsby has an issue with a plugin modifying nodes that "it didn't create".  It seems to only apply when `gatsby-node` is found in the project root; it works fine when it is located in a sub directory.

Perhaps, because of this, in order to use a plugin like this, storing the configuration files in a sub-directory should be mandatory.  That could, potentially, raise compatibility concerns with various other 3rd party plugins, or any Gatsby process that requires the presence of these files in the project root.  My testing thus far hasn't exposed compatibility concerns like that yet, but I would wager a guess that they exist.

I'm not sure yet if there's a decent, and stable, fix for this.  Perhaps, in a scenario where a certain config file is required to be in the root, a "split" could be set up.  The bulk of the work could be done in Typescript, in a sub-directory, and a root copy/stub could be created for compatibility with whatever process needs it.  I really not a fan of having to maintain split configurations, though; that's definitely something I'm trying to avoid.

More investigation is required.

cc/ @d4rekanguok - _thought you might be interested in my findings on this particular subject_

**Comment by d4rekanguok** [comment]
I'm looking into this now. Have you tried using something like  `createNodeField` & add a field to a node which belongs to another plugin, like say MarkdownRemark?

**Comment by Js-Brecht** [comment]
> I'm looking into this now. Have you tried using something like `createNodeField` & add a field to a node which belongs to another plugin, like say MarkdownRemark?

The only way I've been able to make it work successfully was by putting `gatsby-node` in a subdirectory.  Then, there are no node ownership conflicts.  I haven't found any redux store actions yet that cause problems when it's set up this way.

I still need to go analyze the code that does the ownership checks.  It seems a little odd to me that just moving `gatsby-node` out of the root fixes the issue.  This plugin essentially acts like a theme, and theme's are capable of performing the same actions as the root project.  So all of the plugins that are run (by extension, all of their created nodes), and everything run from `gatsby-node`, should all belong to this plugin.  The root project's `gatsby-node` is `require()`'d and returned by this plugin's `gatsby-node`, so Gatsby must be picking up the path of the `require()`'d file somewhere, and determining that there's an ownership conflict.

> Im trying out something with my own setup (not via this plugin), and it seems like it still works despite Gatsby throwing an error! Perhaps we can ignore this.

TBH, I didn't even try to continue after seeing the errors :man_shrugging:.  I wanted to avoid any "scary errors" for the sake of the end-users, but I still leave it up to them how they want to set up their project.. I just recommend using a sub-directory.

I have been tossing around ideas for how to implement this in the core.  I think that would be the best way to solve these issues.  I think there's also plans for Gatsby v3 to let you tell it where you put your `gatsby-*` files (it's on the wishlist, anyway), so that's going to solve my wish to move them out of the root.  This entire plugin is going to become irrelevant pretty soon, I think.

**Comment by JosXa** [comment]
The documentation at https://github.com/Js-Brecht/gatsby-plugin-ts-config#extended-usage suggests to use a "dot folder" named `.gatsby`:

```typescript
// gatsby-config.js
const { generateConfig } = require('gatsby-plugin-ts-config');
module.exports = generateConfig({
    projectRoot: __dirname, // <- not required.  If omitted, projectRoot will be process.cwd()
    configDir: '.gatsby'
});
```

I ran into troubles with this in combination with `gatsby-plugin-typegen`, as it outputs a global, non-importable module declaration where the references cannot be found because by default TypeScript does not include any sources from folders starting with a dot. I suggest changing this or clarifying in the readme that having a dotted folder is going to require extra work in `tsconfig.json`.
