### ISSUE TITLE
Error parsing .tsx files

### ISSUE THREAD

**Issue by mckelveygreg** [Js-Brecht/gatsby-plugin-ts-config#21]
Hey! 
Excited to get my config files in Typescript, but I ran in to a hiccup importing a constant from a `.tsx` file. 
```
 Error: [gatsby-plugin-ts-config] An error occurred while reading your gatsby-node!
  [BABEL] <my-path>.../src/utils/constants.tsx: @babel/preset-typescript: isTSX:true requires allExtensions:true (While
 processing:   "<my-path>.../node_modules/@babel/preset-typescript/lib/index.js")
```
I can't find a way to enable 
```
options: {
  isTSX: true,
  allExtensions: true,
},
```
somewhere....
I tried setting it in both my `gatsby-config.js` and a `.babelrc`
```
gatsby-config.js
babel: {
      presets: [
        [
          require.resolve("@babel/preset-typescript"),
          {
            name: "@babel/preset-typescript",
            options: {
              isTSX: true,
              allExtensions: true,
            },
          },
          "override",
        ],
      ],
```
```
// .babelrc
{
  "presets": [
    [
      "@babel/preset-typescript",
      {
        "isTSX": true,
        "allExtensions": true
      },
      "test"
    ]
  ]
}
```

**Comment by Js-Brecht** [comment]
Hey @mckelveygreg, thanks for reporting this.  I seem to have forgotten that option in the babel config.

Can you try `gatsby-plugin-ts-config@next` and let me know if it fixes the problem?

**Comment by mckelveygreg** [comment]
@Js-Brecht Works great!! Thanks for the speedy reply! And I even saw that section of the code you fixed, but didn't realize it was missing either 🙃

**Comment by Js-Brecht** [comment]
Published as `gatsby-plugin-ts-config@latest`
