### ISSUE TITLE
The resolve prop override breaks some default Gatsby behavior

### ISSUE THREAD

**Issue by phil-lgr** [Js-Brecht/gatsby-plugin-ts-config#27]
https://github.com/Js-Brecht/gatsby-plugin-ts-config/blob/218f88c6d895958c3ad7d7564ec4c7f26abbae26/src/gatsby/gatsby-config.ts#L102

I notice that I couln't override `gatsby-plugin-page-creator` with this plugin

The reason is, Gatsby will compare the resolve prop like here:

https://github.com/akshayymahajan/gatsby/blob/05d65363bcd2a37fc65ca619c62279cbd9ba62b2/packages/gatsby/src/bootstrap/load-plugins/load.js#L224

```js
        plugin.resolve === `gatsby-plugin-page-creator` &&
```

**Comment by phil-lgr** [comment]
Looks like #24 will fix this

**Comment by Js-Brecht** [comment]
@phil-lgr I have a feeling that the Gatsby team will not accept the PR for exposing new plugin config api.  If you are using `yarn` or `npm`, I could probably include a flag for now to turn off the plugin path resolution, since it is mostly needed for `pnpm` and `yarn2`

**Comment by arteforme** [comment]
Just ran into this exact issue.  Awesome to see this will be fixed in the next version.  For now, here's what I did in `gatsby-config.js` to get around it:

```
const { generateConfig } = require('gatsby-plugin-ts-config');

const config = generateConfig({
  configDir: 'gatsby',
});

config.plugins.push({
  resolve: `gatsby-plugin-page-creator`,
  options: {
    path: `${__dirname}/src/pages`,
    ignore: [
      '**/components/**',
     // other patterns go here
    ],
  },
});

module.exports = config;
```
