### ISSUE TITLE
Attempting to link plugin gatsby-source-filesystem to project gatsby-pages failed.

### ISSUE THREAD

**Issue by marcus13371337** [Js-Brecht/gatsby-plugin-ts-config#48]
Hello,

I'm trying to use this plugin, but I'm encountering the following problem:
```
Error: [gatsby-plugin-ts-config]: [gatsby-plugin-ts-config]: Attempting to link plugin gatsby-source-filesystem to project gatsby-pages failed.
  Plugin gatsby-source-filesystem has already been linked
```

This is my config:
```
import { FileSystemConfig } from 'gatsby-source-filesystem';

includePlugins<FileSystemConfig | string>([
  {
    resolve: 'gatsby-source-filesystem',
    options: {
      name: 'product',
      path: `${STORAGE_PATH}/products`,
      ignore: ['**/.git', '.git'],
    },
  },
  {
    resolve: 'gatsby-source-filesystem',
    options: {
      name: 'content',
      path: `${STORAGE_PATH}/contentful`,
      ignore: ['**/.git', '.git'],
    },
  },
```

What am I doing wrong?

**Comment by Js-Brecht** [comment]
Hi @marcus13371337, thanks for reporting this.  You aren't doing anything wrong.  It just needs to be less strict when linking plugins

**Comment by Js-Brecht** [comment]
Should be able to get a fix out tomorrow I think

**Comment by Js-Brecht** [comment]
I'm sorry for the delay @marcus13371337.  I've been swamped and then I got sick.  I'm pushing that fix now

**Comment by Js-Brecht** [comment]
Launched in `gatsby-plugin-ts-config@2.1.3`

**Comment by marcus13371337** [comment]
Amazing thanks for your fix! Wonderful! 🎉

**Comment by marcus13371337** [comment]
Hm, I'm getting another error now:
```
Uncaught TypeError: plugin.plugin[api] is not a function
    at eval (api-runner-browser.js:26)
    at Array.map (<anonymous>)
    at exports.apiRunner (api-runner-browser.js:17)
    at eval (root.js:100)
    at Module../.cache/root.js (commons.js:4401)
```
It seems to be something with that the files are ES6-modules when trying to wrapRootElement:
![Screenshot 2021-10-05 at 11 33 59](https://user-images.githubusercontent.com/17770075/135998408-4682da84-08c1-4f6c-9fce-74714ed87ca8.png)

It could be me who made an error with the gatsby-browser/gatsby-ssr config files. I just added them as js-files like this:
`gatsby-browser.js`
```
const wrapRootElement = require('./src/wrapRootElement');
const wrapPageElement = require('./src/wrapPageElement');

module.exports = { wrapRootElement, wrapPageElement };
```
Are there any docs on how to handle those config files?

**Comment by Js-Brecht** [comment]
I would have to see what `./src/wrapRootElement` looks like.

One comment I have is that you can write `gatsby-browser` and `gatsby-ssr` in ES6 or Typescript.

Check what kind of exports `./src/wrapRootElement` and `./src/wrapPageElement` have.

If you did
```js
export const wrapPageElement
// or
export default wrapPageElement
```

Then you would need to do this in CJS (respectively)
```js
const { wrapPageElement } = require("./src/wrapPageElement");
// or
const wrapPageElement = require("./src/wrapPageElement").default
```

However, since you can write them in ES6 or TS:
```js
export { wrapPageElement } from "./src/wrapPageElement";
// or
export { default as wrapPageElement } from "./src/wrapPageElement";
```

**Comment by marcus13371337** [comment]
Ah cool! I understand, will try that! But if I write them in typescript, do I need to do something similar to:
gatsby-node.js
```
const { useGatsbyNode } = require('gatsby-plugin-ts-config');

// eslint-disable-next-line react-hooks/rules-of-hooks
module.exports = useGatsbyNode('./config/gatsby-node');
```

**Comment by Js-Brecht** [comment]
No, Gatsby hits those with Webpack, and it turns on Typescript support for bundling by default.  This plugin doesn't touch those two files

**Comment by marcus13371337** [comment]
Ok cool!

**Comment by marcus13371337** [comment]
Works like a charm! Thank you soo much!

**Comment by Js-Brecht** [comment]
You're welcome 🙂
