### ISSUE TITLE
createPages runs indefinitely

### ISSUE THREAD

**Issue by Pernick** [Js-Brecht/gatsby-plugin-ts-config#54]
Hello, I have just started using this plugin. Great stuff, allowed me to reuse some of my TypeScript config.

I am currently having one big issue while rewriting the app to new version. `createPages` scripts runs indefinitely while using the plugin. Works normally with `createPages` script in `gatsby-node.js`.

I will create repo to reproduce the error and update this issue when I do.

EDIT: https://github.com/Pernick/gatsby-ts-config-create-pages-stuck

While I am doing that - I just wanted to ask if anyone encountered this issue with this plugin specifically. I have noticed that this issue occurred for many people due to different reasons, but in this case I can confirm it being caused by `gatsby-plugin-ts-config`.

Some additional info:
- issue prevails with named and default exports
- issue prevails for both `babel` and `ts-node` types

**Comment by Pernick** [comment]
After more digging, I actually found out, this has nothing to do with `gatsby-plugin-ts-config`. I thought so, because disabling it helped, but other factor was there as well.

The solution to this in my case was this:

From `gatsby-node.ts` I exported this function

```
export const createPages: GatsbyNode['createPages'] = async (args, options, callback) => {
    await createBlogPages(args, options, callback);
}
```

But the definition of `createBlogPages` only used the first parameter `args`

```
export const createBlogPages: GatsbyNode['createPages'] = async ({
  actions: { createPage },
  graphql,
  reporter,
}) => {}
```

Not using the rest of the parameters caused the hang up.

By switching to this, the problem was solved:

```
export const createPages: GatsbyNode['createPages'] = async a => {
  await createBlogPages(a);
};

export const createBlogPages = async ({
  actions: { createPage },
  graphql,
  reporter,
}: CreatePagesArgs) => {}
```

**Comment by Js-Brecht** [comment]
If you define the function with three parameters (I.e. the `callback`) Gatsby will wait for you to call the `callback` before continuing.

Something like this would have also worked:

```ts
export const createPages: GatsbyNode['createPages'] = async (args, options, callback) => {
    await createBlogPages(args, options, callback);
    callback();
}
```
