### ISSUE TITLE
Support for Gatsby 4.x.x

### ISSUE THREAD

**Issue by patrickbenjamin1** [Js-Brecht/gatsby-plugin-ts-config#60]
We're now on Gatsby 4.18.0, but this plugin only supports 2.x.x or 3.x.x, giving the following error on install

```
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: simple-gatsby-boilerplate@undefined
npm ERR! Found: gatsby@4.18.0
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"4.18.0" from the root project
```

I attempted to fix it by adding the following to my package.json...

```json
{
  "overrides": {
    "gatsby-plugin-ts-config": {
      "gatsby": "^4.18.0"
    }
  }
}
```

...to force the versions but this causes the following error during `gatsby build`:

```
11:19:04 AM:
ERROR We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.

11:19:04 AM:
11:19:04 AM:
  Error: [gatsby-plugin-ts-config]: Debug Failure. False expression: Non-string   value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping packa  ge working with an outdated `resolveTypeReferenceDirectives` signature. This i  s probably not a problem in TS itself.
```

with `typescript@4.7.4`

**Comment by patrickbenjamin1** [comment]
Is this plugin still supported? I noticed there hasn't been a commit since October last 2021

**Comment by patrickbenjamin1** [comment]
Just noticed there are two duplicate issues - closing

**Comment by Js-Brecht** [comment]
> Is this plugin still supported? I noticed there hasn't been a commit since October last 2021

Unfortunately, there were some changes in the core that made it difficult, if not impossible, for this plugin to function as it currently is.  It would have to be stripped down to basically nothing, at which point it makes more sense to just use the core’s built in config transpiler.

Eventually I may rewrite the whole thing… it’s just not really worth the time at the moment.
